### ISSUE TITLE
add to stackage

### ISSUE THREAD

**Issue by legrostdg** [plow-technologies/servant-aeson-specs#4]
Is there a plan to add servant-aeson-specs to stackage? It would be great!

**Comment by mchaver** [comment]
There are a few things I want to clean up first. I made a fork of this package (hspec-golden-aeson) that focuses on improving the Aeson golden tests and gives you a lot more flexibility (number of times you are testing types, testing all constructors, names of folders, ways to avoid clashes between same named types in different modules,etc.) I want to remove the roundtrip and golden tests from servant-aeson-specs because the same ones exist in hspec-golden-aeson, then make hspec-golden-aeson
a dependency of servant-aeson-specs.

I'll probably push 0.2.0.0 of hspec-golden-aeson before the end of the week. Need to add better documentation.
https://github.com/plow-technologies/hspec-golden-aeson
https://hackage.haskell.org/package/hspec-golden-aeson

**Comment by soenkehahn** [comment]
@mchaver: Doesn't the current version allow you to test all constructors? It simply relies on writing the correct `Arbitrary` instance, doesn't it?

Also, why is it better to have the golden tests as a separate package?

**Comment by soenkehahn** [comment]
@mchaver: And is there a reason to wait for your changes before putting this on stackage? Since it's on hackage already.

**Comment by mchaver** [comment]
@soenkehahn 

Reason to separate it is because golden aeson testing is useful outside the context of servant. So it makes sense to have package functions that focus on just that aspect.

You can use it with `Arbitrary` to test the constructors if you set it up appropriately but I have the golden aeson setup to test in two ways. One is the same as servant-aeson-specs, just using the Arbitrary definition, the other is a Typeclass instance that can be made generically, it will create arbitrary values for each constructor. This is very useful for sum types. It will put instances for each constructor in a file in a directory named after the type. It is easier to pinpoint issues with individual sum types.

I didn't realize it was on hackage already. Feel free to add it to stackage. Otherwise I'll do it once I get to this.

**Comment by soenkehahn** [comment]
@mchaver: Oh, yes, forgot about the dependency on `servant`.

**Comment by mchaver** [comment]
I made a pull request to stackage to have it added.

**Comment by soenkehahn** [comment]
@mchaver: I can't find the PR. Can you give me a link, please?
